In [64]:
#Errinhos....
import pandas as pd
import numpy as np
import numpy as np
from sklearn.naive_bayes import GaussianNB

In [65]:
#TREINAR GAUSS1,GAUSS2 e GAUSS3 COM View1, View2 E View3
# combinar os Gauss pela regra da soma


In [66]:
"""Pegando os dados de treinamento de fac - CRISP"""
X_fac_original = pd.read_csv('datasets/mfeat-fac-crisp.csv', delimiter =',', header=None)
X_fac_original.head()

0      1      2      3      4      5     6    7    8    9    ...    207  \
0   98.0  236.0  531.0  673.0  607.0  647.0   2.0  9.0  3.0  6.0  ...  536.0   
1  121.0  193.0  607.0  611.0  585.0  665.0   7.0  9.0  2.0  4.0  ...  458.0   
2  115.0  141.0  590.0  605.0  557.0  627.0  12.0  6.0  3.0  3.0  ...  498.0   
3   90.0  122.0  627.0  692.0  607.0  642.0   0.0  6.0  4.0  5.0  ...  549.0   
4  157.0  167.0  681.0  666.0  587.0  666.0   8.0  6.0  1.0  4.0  ...  525.0   

     208    209   210   211   212   213   214   215  216  
0  628.0  632.0  18.0  36.0   8.0  15.0  12.0  13.0    1  
1  570.0  634.0  15.0  32.0  11.0  13.0  15.0  11.0    1  
2  572.0  656.0  20.0  35.0  16.0  14.0  13.0   6.0    1  
3  628.0  621.0  16.0  35.0   7.0  12.0  15.0   9.0    7  
4  568.0  653.0  16.0  35.0  10.0  15.0  13.0  13.0    1  

[5 rows x 217 columns]

In [67]:
#Pega todas as linhas de todos os exemplos até a coluna 216 (exclusive) . Na prática (o que se quer) pega até a coluna 215
#Esses são nossos dados sem a rotulação de classes (label)
X_view1_fac = X_fac_original.iloc[:, 0: 216].get_values() # retorna como uma matriz e não como dataframe 
X_view1_fac

array([[ 98., 236., 531., ...,  15.,  12.,  13.],
       [121., 193., 607., ...,  13.,  15.,  11.],
       [115., 141., 590., ...,  14.,  13.,   6.],
       ...,
       [337., 299., 852., ...,  15.,  17.,  21.],
       [247., 261., 866., ...,  13.,  15.,  15.],
       [355., 379., 867., ...,  12.,  12.,  20.]])

In [68]:
#Pega a última coluna com todas suas linhas. Isso será nosso array de TRUE LABEL, com a marcação correta das classes
y_view1_fac = X_fac_original.iloc[:, 216].get_values()
y_view1_fac

array([1, 1, 1, ..., 3, 3, 6], dtype=int64)

In [69]:
#Naive Bayes Classifier
GaussClf1 = GaussianNB()

In [70]:
#dados de treino x com os true labels de y para TREINAR
GaussClf1.fit(X_view1_fac, y_view1_fac)

GaussianNB(priors=None, var_smoothing=1e-09)

In [71]:
acuracia_atual = clf.score(X_view1_fac, y_view1_fac)
acuracia_atual

0.593

In [72]:
"""Pegando os dados de treinamento de FOU - CRISP"""
X_fou_original = pd.read_csv('datasets/mfeat-fou-crisp.csv', delimiter =',', header=None)
X_fou_original.head()

0         1         2         3         4         5         6   \
0  0.065882  0.197312  0.103826  0.270362  0.616078  0.035856  0.424572   
1  0.049142  0.175971  0.105515  0.227095  0.599280  0.041217  0.431078   
2  0.034172  0.227649  0.108766  0.127697  0.612494  0.056554  0.470639   
3  0.062336  0.217979  0.080243  0.289592  0.546316  0.045779  0.425545   
4  0.061970  0.198358  0.111239  0.253460  0.608455  0.023631  0.415246   

         7         8         9   ...        67        68        69        70  \
0  0.089701  0.367773  0.037065  ...  0.113374  0.074343  0.281666  0.067795   
1  0.096801  0.326739  0.059661  ...  0.069337  0.045386  0.254264  0.045447   
2  0.041903  0.324267  0.044569  ...  0.218842  0.041087  0.360464  0.047154   
3  0.022841  0.331454  0.119052  ...  0.085479  0.087658  0.151880  0.075950   
4  0.091866  0.309310  0.049142  ...  0.106960  0.032283  0.248565  0.015674   

         71        72        73        74        75  76  
0  0.344182  0.038963  0.394366  0.049971  0.344871   1  
1  0.335659  0.021719  0.445277  0.083978  0.354092   1  
2  0.377408  0.052099  0.445029  0.071234  0.261465   1  
3  0.293462  0.022675  0.408291  0.063010  0.401376   7  
4  0.386276  0.039481  0.434701  0.069218  0.405403   1  

[5 rows x 77 columns]

In [73]:
#Pega todas as linhas de todos os exemplos até a coluna 216 (exclusive) . Na prática (o que se quer) pega até a coluna 215
#Esses são nossos dados sem a rotulação de classes (label)
X_view2_fou = X_fou_original.iloc[:, 0: 76].get_values() # retorna como uma matriz e não como dataframe 
X_view2_fou

array([[0.06588172, 0.19731169, 0.10382563, ..., 0.39436572, 0.04997072,
        0.34487096],
       [0.04914215, 0.17597068, 0.10551464, ..., 0.44527711, 0.08397801,
        0.35409193],
       [0.03417192, 0.22764888, 0.10876636, ..., 0.44502912, 0.07123367,
        0.2614646 ],
       ...,
       [0.33560596, 0.318426  , 0.25794822, ..., 0.14157604, 0.03877594,
        0.11459086],
       [0.25390962, 0.17120241, 0.30262199, ..., 0.23032164, 0.10366427,
        0.13000271],
       [0.27157485, 0.14903681, 0.23275253, ..., 0.27576948, 0.02107437,
        0.08524072]])

In [74]:
#Pega a última coluna com todas suas linhas. Isso será nosso array de TRUE LABEL, com a marcação correta das classes
y_view2_fou = X_fou_original.iloc[:, 76].get_values()
y_view2_fou

array([1, 1, 1, ..., 3, 3, 6], dtype=int64)

In [75]:
#Naive Bayes Classifier
GaussClf2 = GaussianNB()

In [76]:
#dados de treino x com os true labels de y para TREINAR
GaussClf2.fit(X_view2_fou, y_view2_fou)

GaussianNB(priors=None, var_smoothing=1e-09)

In [77]:
acuracia_atual = clf.score(X_view1_fac, y_view1_fac)
acuracia_atual

0.593

In [78]:
"""Pegando os dados de treinamento de kar - CRISP"""
X_kar_original = pd.read_csv('datasets/mfeat-kar-crisp.csv', delimiter =',', header=None)
X_kar_original.head()

0          1          2         3         4         5         6   \
0 -10.297008 -11.666789  11.560669 -2.081316  4.044656  4.086815 -2.558072   
1  -5.036009 -12.885333   0.161155  0.592460  3.123534  4.220469 -6.411771   
2  -9.639157  -6.655898   0.388687 -1.717650  0.300346  3.400769 -7.240785   
3  -6.650375  -7.043851   4.104350 -2.342780  3.494658  3.924822 -9.874812   
4 -10.664524 -10.974133   0.194391  0.453885  2.193088 -3.304663 -8.376592   

         7         8         9   ...        55        56        57        58  \
0 -8.476935  2.138135  3.503082  ...  0.921927  0.496387 -0.643667  0.284104   
1 -6.335328 -0.244622  1.346073  ...  2.938791  1.429883 -2.336344  1.281628   
2 -1.659405 -0.874005  4.153403  ... -0.023028 -0.025265  1.259838 -0.441360   
3 -6.556576 -1.364269  1.153308  ... -1.043815 -0.204508 -1.981150  0.982438   
4 -4.241146  2.964818 -0.949622  ...  1.448160 -1.254907 -3.481295 -0.563889   

         59        60        61        62        63  64  
0  0.286555  0.348625  1.814691 -1.351353 -0.473910   1  
1 -0.098321  0.582357  0.485792  0.642451  0.613107   1  
2 -0.960094  1.995843  1.097748  0.827182 -1.767840   1  
3 -0.144233 -1.449328 -0.913552 -0.771735  0.304992   7  
4  1.529335  0.510399  0.298318 -0.943213  1.149847   1  

[5 rows x 65 columns]

In [82]:
X_view3_kar = X_kar_original.iloc[:, 0: 64].get_values() # retorna como uma matriz e não como dataframe 
print(X_view3_kar)

[[-1.02970076e+01 -1.16667891e+01  1.15606690e+01 ...  1.81469083e+00
  -1.35135269e+00 -4.73910360e-01]
 [-5.03600883e+00 -1.28853331e+01  1.61155220e-01 ...  4.85791740e-01
   6.42450570e-01  6.13107090e-01]
 [-9.63915730e+00 -6.65589762e+00  3.88686870e-01 ...  1.09774804e+00
   8.27182050e-01 -1.76784039e+00]
 ...
 [ 1.88161314e+00 -9.65088081e+00  3.17780410e-01 ... -4.39636590e-01
   2.87012700e-01 -4.20792850e-01]
 [-1.53088582e+00 -1.01837750e+01 -1.05586362e+00 ...  1.40521359e+00
   4.35513970e-01 -2.25426380e-01]
 [ 1.12516336e+01 -5.95969105e+00  5.36724520e+00 ...  7.91150000e-03
   7.63970730e-01  4.03685800e-02]]
