In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.metrics.pairwise import euclidean_distances


In [2]:
# START OF MAIN CODE ---------------------------------------------------------------------------------########################

In [3]:
# MFEAT-KAR -----------------------------------------------------------------------------#############


In [4]:
dados_kar = pd.read_csv('C:/datasets/mfeat-kar', delimiter='\s+', header=None)


In [5]:
numLinhas_kar = dados_kar.shape[0]
numColunas_kar = dados_kar.shape[1]

numLinhas_kar
        

2000

In [6]:
numColunas_kar

64

In [7]:
#Normalizando com média 0 e desvio padrão 1
dados_kar_normalizados = preprocessing.scale(dados_kar)
dados_kar_normalizados

array([[-1.19354001, -1.92157541,  1.83653986, ...,  2.07224197,
        -1.78357951, -0.28517412],
       [-0.50934996, -2.1347926 , -0.2089806 , ...,  0.5951963 ,
         0.45132277,  0.7765261 ],
       [-1.10798694, -1.0447846 , -0.16815248, ...,  1.2753739 ,
         0.65839276, -1.54896781],
       ...,
       [ 0.39028304, -1.56883781, -0.18087589, ..., -0.43339942,
         0.05290387, -0.23329375],
       [-0.05351061, -1.66208204, -0.42736157, ...,  1.61711592,
         0.21936254, -0.04247747],
       [ 1.60884916, -0.92296445,  0.72519641, ...,  0.06404164,
         0.58753766,  0.21712698]])

In [8]:
# Calcula a distância euclidiana para o numero de colunas (64)
matrizDistanciaEucKar = euclidean_distances(dados_kar_normalizados, dados_kar_normalizados)
matrizDistanciaEucKar

array([[ 0.        ,  8.53591548,  9.19233846, ..., 10.56634116,
         8.71710808, 10.2453903 ],
       [ 8.53591548,  0.        ,  9.84991062, ..., 11.01188734,
         8.66078139, 10.69968324],
       [ 9.19233846,  9.84991062,  0.        , ...,  9.85446776,
         8.70168007, 10.90369135],
       ...,
       [10.56634116, 11.01188734,  9.85446776, ...,  0.        ,
         8.37612444, 11.44533001],
       [ 8.71710808,  8.66078139,  8.70168007, ...,  8.37612444,
         0.        ,  9.4123038 ],
       [10.2453903 , 10.69968324, 10.90369135, ..., 11.44533001,
         9.4123038 ,  0.        ]])

In [9]:
# MFEAT-FOU -----------------------------------------------------------------------------#############


In [10]:

dados_fou = pd.read_csv('C:/datasets/mfeat-fou', delimiter='\s+', header=None)


In [11]:
numLinhas_fou = dados_fou.shape[0]
numColunas_fou = dados_fou.shape[1]

numLinhas_fou


2000

In [12]:
numColunas_fou

76

In [13]:
#Normalizando com média 0 e desvio padrão 1
dados_fou_normalizados = preprocessing.scale(dados_fou)
dados_fou_normalizados

array([[-1.30245067, -1.02163771, -1.20012317, ...,  0.96643443,
        -1.09773269,  1.03419088],
       [-1.48465024, -1.14276502, -1.18787917, ...,  1.35514092,
        -0.70064333,  1.10923272],
       [-1.64759166, -0.84944988, -1.16430673, ...,  1.35324753,
        -0.84945383,  0.35541552],
       ...,
       [ 1.63332598, -0.33421707, -0.08285457, ..., -0.96360498,
        -1.2284496 , -0.83986832],
       [ 0.74411332, -1.16982877,  0.24099543, ..., -0.28603576,
        -0.47077484, -0.71444403],
       [ 0.93638811, -1.29563629, -0.26550368, ...,  0.06095674,
        -1.43514367, -1.07872483]])

In [14]:
# Calcula a distância euclidiana para o numero de colunas
matrizDistanciaEucFou = euclidean_distances(dados_fou_normalizados, dados_fou_normalizados)
matrizDistanciaEucFou

array([[ 0.        ,  8.06562613,  7.80320571, ..., 12.01833333,
        10.76930078, 11.90876743],
       [ 8.06562613,  0.        ,  5.84868677, ..., 14.38830699,
        12.68291834, 13.70439057],
       [ 7.80320571,  5.84868677,  0.        , ..., 13.92577914,
        12.54125069, 12.92238358],
       ...,
       [12.01833333, 14.38830699, 13.92577914, ...,  0.        ,
        10.95241111, 12.28562708],
       [10.76930078, 12.68291834, 12.54125069, ..., 10.95241111,
         0.        ,  9.42782411],
       [11.90876743, 13.70439057, 12.92238358, ..., 12.28562708,
         9.42782411,  0.        ]])

In [15]:
# MFEAT-FAC -----------------------------------------------------------------------------#############


In [16]:
dados_fac = pd.read_csv('C:/datasets/mfeat-fac', delimiter='\s+', header=None)


In [17]:
numLinhas_fac = dados_fou.shape[0]
numColunas_fac = dados_fou.shape[1]

numLinhas_fac

2000

In [18]:
numColunas_fac

76

In [19]:
#Normalizando com média 0 e desvio padrão 1
dados_fac_normalizados = preprocessing.scale(dados_fac)
dados_fac_normalizados


C:\Users\Allan Santos\.conda\envs\AM\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: Data with input dtype int64 were all converted to float64 by the scale function.
  


array([[-1.90735868, -0.79274325, -1.74027935, ...,  1.17558452,
        -0.85869511, -0.09760513],
       [-1.65531116, -1.18579904, -1.19783496, ...,  0.40013299,
         0.65264858, -0.52900903],
       [-1.72106269, -1.66112232, -1.31917121, ...,  0.78785876,
        -0.35491388, -1.60751878],
       ...,
       [ 0.71174385, -0.21687082,  0.55083443, ...,  1.17558452,
         1.66021104,  1.62801046],
       [-0.27452907, -0.56422244,  0.65075839, ...,  0.40013299,
         0.65264858,  0.33379877],
       [ 0.90899844,  0.51439577,  0.65789582, ...,  0.01240722,
        -0.85869511,  1.41230851]])

In [20]:
# Calcula a distância euclidiana para o numero de colunas (76)
matrizDistanciaEucFac = euclidean_distances(dados_fac_normalizados, dados_fac_normalizados)
matrizDistanciaEucFac

array([[ 0.        ,  8.97733318, 10.26384656, ..., 20.26248467,
        18.94151479, 22.74257104],
       [ 8.97733318,  0.        ,  8.1396145 , ..., 18.73059065,
        16.40316683, 20.95345162],
       [10.26384656,  8.1396145 ,  0.        , ..., 20.01701331,
        17.18634326, 22.86643324],
       ...,
       [20.26248467, 18.73059065, 20.01701331, ...,  0.        ,
         9.52418856, 12.73072781],
       [18.94151479, 16.40316683, 17.18634326, ...,  9.52418856,
         0.        , 15.7032138 ],
       [22.74257104, 20.95345162, 22.86643324, ..., 12.73072781,
        15.7032138 ,  0.        ]])

In [21]:
# END OF MAIN CODE ---------------------------------------------------------------------------------########################

In [22]:
# FUNÇÃO DE CRITÉRIO -> J(G, A, U) -----------------------------------------------------------------########################

In [23]:
np.array([1, 2, 3])

array([1, 2, 3])

In [30]:
a = np.matrix([[1,2,3],[4,5,6]])
b = np.matrix([[7,8,9],[10,11,12]])

In [31]:
a

matrix([[1, 2, 3],
        [4, 5, 6]])

In [32]:
b

matrix([[ 7,  8,  9],
        [10, 11, 12]])

In [34]:
np.array([a,b])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])