In [176]:
from sklearn import metrics
 
import gensim.models as g
import codecs

In [197]:
model_src="../../models/enwiki_dbow/doc2vec.bin"
test_docs_src="data/input_test_docs.txt"

In [198]:
#inference hyper-parameters
start_alpha=0.01
infer_epoch=1000

In [199]:
#load model
m = g.Doc2Vec.load(model_src)
#read the file: put the sentences in a list: each position contains a array with a unique sentence
test_docs = [ x.strip().split() for x in codecs.open(test_docs_src, "r", "utf-8").readlines() ]

In [200]:
type(test_docs)

list

In [201]:
print (test_docs)

[['And', 'he', 'had', 'two', 'wives;', 'the', 'name', 'of', 'the', 'one', 'was', 'Hannah,', 'and', 'the', 'name', 'of', 'the', 'other', 'Peninnah:', 'and', 'Peninnah', 'had', 'children,', 'but', 'Hannah', 'had', 'no', 'children.', 'And', 'this', 'man', 'went', 'up', 'out', 'of', 'his', 'city', 'yearly', 'to', 'worship', 'and', 'to', 'sacrifice', 'unto', 'the', 'LORD', 'of', 'hosts', 'in', 'Shiloh.', 'And', 'the', 'two', 'sons', 'of', 'Eli,', 'Hophni', 'and', 'Phinehas,', 'the', 'priests', 'of', 'the', 'LORD,', 'were', 'there.', 'And', 'when', 'the', 'time', 'was', 'that', 'Elkanah', 'offered,', 'he', 'gave', 'to', 'Peninnah', 'his', 'wife,', 'and', 'to', 'all', 'her', 'sons', 'and', 'her', 'daughters,', 'portions:But', 'unto', 'Hannah', 'he', 'gave', 'a', 'worthy', 'portion;', 'for', 'he', 'loved', 'Hannah:', 'but', 'the', 'LORD', 'had', 'shut', 'up', 'her', 'womb.', 'And', 'her', 'adversary', 'also', 'provoked', 'her', 'sore,', 'for', 'to', 'make', 'her', 'fret,', 'because', 'the', 'L

In [202]:
#How many sentences?
len(test_docs)

4

In [203]:
# X is a list containing the embeddings of all sentences
X=[]
for d in test_docs:
     
    X.append( m.infer_vector(d, alpha=start_alpha, steps=infer_epoch) )

In [204]:
type(X)

list

In [205]:
#two sentences..two embeddings
len(X)

4

In [206]:
X

[array([ 0.4346355 ,  0.04547512, -0.14333366, -0.03401601, -0.30435765,
        -0.89043885,  0.8146765 , -0.21532129, -0.434865  ,  0.06123487,
        -1.4811046 , -0.24115796,  0.40961847, -0.02451061, -0.03153168,
         0.0101401 , -0.3518312 , -0.6323225 ,  0.18119055,  0.02466499,
        -0.21652596, -0.03637685,  0.14946146, -0.82926303,  0.8473215 ,
         0.15318656, -0.55738837, -0.062562  , -0.21973774,  0.4172744 ,
        -0.40917033,  1.0568968 , -0.24303478, -0.3358892 , -0.13551529,
         0.21903725,  0.39047077, -0.21907502, -0.4955445 , -0.6684986 ,
        -0.56067574,  0.03028536, -0.80452067, -0.09699612,  0.21526882,
         0.01835454, -0.62912244, -0.26138029,  0.01424315, -1.0463864 ,
        -0.27082425, -0.68880385,  0.43944773,  0.04892408, -0.3891651 ,
        -0.5365588 , -0.21365961,  0.46365008,  0.03610504, -0.3734966 ,
         0.47850817, -1.2609042 , -0.24135986, -0.8539    ,  0.81653565,
         0.12235221, -0.32896447, -0.9746753 ,  0.0

In [207]:
#size of embedding 1 from sentence 1
len(X[0])

300

In [208]:
#size of embedding 2 from sentence 2
len(X[1])

300

In [209]:
#size of embedding n from sentence n
#len(X[2])

In [210]:
k=3
 
from sklearn.cluster import Birch
 
brc = Birch(branching_factor=50, n_clusters=k, threshold=0.1, compute_labels=True)
brc.fit(X)

C:\Users\Allan Santos\.conda\envs\AM\lib\site-packages\sklearn\cluster\birch.py:629: ConvergenceWarning: Number of subclusters found (2) by Birch is less than (3). Decrease the threshold.
  % (len(centroids), self.n_clusters), ConvergenceWarning)


Birch(branching_factor=50, compute_labels=True, copy=True, n_clusters=3,
   threshold=0.1)

In [211]:
clusters = brc.predict(X)

In [212]:
clusters

array([0, 1, 1, 1])

In [213]:
labels = brc.labels_
labels

array([0, 1, 1, 1])

In [214]:
labels = np.unique(brc.labels_)
labels

array([0, 1])

In [215]:
len(labels)

2

In [216]:
silhouette_score = metrics.silhouette_score(X, labels, metric='euclidean')

ValueError: Found input variables with inconsistent numbers of samples: [4, 2]

In [ ]:
print ("Silhouette_score: ", silhouette_score)

### Sample with Iris dataset using K-Means

In [62]:
from sklearn import datasets
from sklearn.cluster import KMeans
import numpy as np

In [66]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [68]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [98]:
km = KMeans(n_clusters=3)
km.fit(X,y)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [99]:
km.labels_

array([0, 1, 2])

In [70]:
# check how many unique labels do you have
np.unique(km.labels_)
#array([0, 1, 2], dtype=int32)

array([0, 1, 2])

In [77]:
silhouette_score_kmeans = metrics.silhouette_score(X, km.labels_, metric='euclidean')

In [78]:
silhouette_score_kmeans

0.5528190123564091