In [44]:
import pandas as pd
import numpy as np
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import StratifiedKFold

In [45]:
#10 folds para validação cruzada
k_folds = 10

In [46]:
"""Pegando os dados de treinamento de fac - CRISP"""
X_fac_original = pd.read_csv('datasets/mfeat-fac-crisp.csv', delimiter =',', header=None)
X_fac_original.head()

0      1      2      3      4      5     6    7    8    9    ...    207  \
0   98.0  236.0  531.0  673.0  607.0  647.0   2.0  9.0  3.0  6.0  ...  536.0   
1  121.0  193.0  607.0  611.0  585.0  665.0   7.0  9.0  2.0  4.0  ...  458.0   
2  115.0  141.0  590.0  605.0  557.0  627.0  12.0  6.0  3.0  3.0  ...  498.0   
3   90.0  122.0  627.0  692.0  607.0  642.0   0.0  6.0  4.0  5.0  ...  549.0   
4  157.0  167.0  681.0  666.0  587.0  666.0   8.0  6.0  1.0  4.0  ...  525.0   

     208    209   210   211   212   213   214   215  216  
0  628.0  632.0  18.0  36.0   8.0  15.0  12.0  13.0    1  
1  570.0  634.0  15.0  32.0  11.0  13.0  15.0  11.0    1  
2  572.0  656.0  20.0  35.0  16.0  14.0  13.0   6.0    1  
3  628.0  621.0  16.0  35.0   7.0  12.0  15.0   9.0    7  
4  568.0  653.0  16.0  35.0  10.0  15.0  13.0  13.0    1  

[5 rows x 217 columns]

In [76]:
#Pega todas as linhas de todos os exemplos até a coluna 216 (exclusive) . Na prática (o que se quer) pega até a coluna 215
#Esses são nossos dados sem a rotulação de classes (label)
X_fac_train = X_fac_original.iloc[:, 0: 216].get_values() # retorna como uma matriz e não como dataframe 
X_fac_train

array([[ 98., 236., 531., ...,  15.,  12.,  13.],
       [121., 193., 607., ...,  13.,  15.,  11.],
       [115., 141., 590., ...,  14.,  13.,   6.],
       ...,
       [337., 299., 852., ...,  15.,  17.,  21.],
       [247., 261., 866., ...,  13.,  15.,  15.],
       [355., 379., 867., ...,  12.,  12.,  20.]])

In [48]:
#Pega a última coluna com todas suas linhas. Isso será nosso array de true label, com a marcação correta das classes
y_labels = X_fac_original.iloc[:, 216].get_values()
y_labels

array([1, 1, 1, ..., 3, 3, 6], dtype=int64)

In [49]:
#K= 10.. OU SEJA: 10 FOLDS
skf = StratifiedKFold(n_splits=k_folds)

In [50]:
#faz a divisão preservando a percentagem igual de classes por fold
skf.get_n_splits(X_fac_train, y_labels)

10

In [51]:
#Naive Bayes Classifier
clf = GaussianNB()

In [52]:
somatorio_acuracia = 0

In [78]:
for train_index, test_index in skf.split(X_fac_train, y_labels):
    
    """
for de i a K
	pega um fold para validação e o restante para treinamento (o método que faz isso por si)
	treina o modelo com os folds de treinamento e testa com os folds de validação pra ver se a predições estão corretas
	pega a acurácia

pega a média das acurácias"""
    
for train_index, test_index in skf.split(X_fac_train, y_labels):

    """Separando os dados para treino e teste
    X_train, X_test = X_fac_train[train_index], X_fac_train[test_index]
    
    # Separando os folds LABELED para conferir com o treino (y_train) E verificar a acurácia do teste (y_test)
    y_train, y_test = y_labels[train_index], y_labels[test_index]
      
    #Treinando.......................................
    #Treinando o modelo GaussianNB: associando os folds correspondentes para treinamento, OU SEJA, 
    #dados de treino x com os true labels de y para TREINAR
    clf.fit(X_train, y_train)
    
    3Testando.......................................
    
    #Obtendo a acurácia atual: esse método retorna a média de acerto DESSA rodada de testes
    #score: Returns the mean accuracy on the given test data and labels.
    acuracia_atual = clf.score(X_test, y_test)
    
    #Fazendo somatório das acurácias para posterior média
    somatorio_acuracia += acuracia_atual
   
   # print("acuracia_atual:", acuracia_atual)     """

[[138. 206. 629. ...  12.  13.  10.]
 [145. 139. 623. ...  16.  15.  10.]
 [139. 149. 625. ...  12.  13.   7.]
 ...
 [337. 299. 852. ...  15.  17.  21.]
 [247. 261. 866. ...  13.  15.  15.]
 [355. 379. 867. ...  12.  12.  20.]]
[[ 98. 236. 531. ...  15.  12.  13.]
 [121. 193. 607. ...  13.  15.  11.]
 [115. 141. 590. ...  14.  13.   6.]
 ...
 [337. 299. 852. ...  15.  17.  21.]
 [247. 261. 866. ...  13.  15.  15.]
 [355. 379. 867. ...  12.  12.  20.]]
[[ 98. 236. 531. ...  15.  12.  13.]
 [121. 193. 607. ...  13.  15.  11.]
 [115. 141. 590. ...  14.  13.   6.]
 ...
 [337. 299. 852. ...  15.  17.  21.]
 [247. 261. 866. ...  13.  15.  15.]
 [355. 379. 867. ...  12.  12.  20.]]
[[ 98. 236. 531. ...  15.  12.  13.]
 [121. 193. 607. ...  13.  15.  11.]
 [115. 141. 590. ...  14.  13.   6.]
 ...
 [337. 299. 852. ...  15.  17.  21.]
 [247. 261. 866. ...  13.  15.  15.]
 [355. 379. 867. ...  12.  12.  20.]]
[[ 98. 236. 531. ...  15.  12.  13.]
 [121. 193. 607. ...  13.  15.  11.]
 [115. 141. 59

In [ ]:
media_acuracia = somatorio_acuracia / k_folds
media_acuracia