In [1]:
#From: https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html
import numpy as np
from sklearn.naive_bayes import GaussianNB


In [2]:
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])

print(X)

[[-1 -1]
 [-2 -1]
 [-3 -2]
 [ 1  1]
 [ 2  1]
 [ 3  2]]


In [3]:
Y = np.array([1, 1, 1, 2, 2, 2])

print(Y)

[1 1 1 2 2 2]


In [4]:
clf = GaussianNB()

In [5]:
# Treinando, associando X com Y: Pode usar fit ou partial_fit
clf.fit(X, Y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [43]:
#predizendo/classificando/generalizando....
print("predict",clf.predict([[-3, 1]]))

predict [1]


In [44]:
X[0]

array([-1, -1])

In [42]:
print("predict",clf.predict( X[0] ) )

ValueError: Expected 2D array, got 1D array instead:
array=[-1 -1].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [34]:
clf.class_prior_

array([0.5, 0.5])

In [30]:
clf.class_prior_[0]

0.5

In [24]:
clf.predict_proba(X)

array([[9.99999985e-01, 1.52299840e-08],
       [1.00000000e+00, 3.77513581e-11],
       [1.00000000e+00, 5.74952589e-19],
       [1.52299840e-08, 9.99999985e-01],
       [3.77513581e-11, 1.00000000e+00],
       [5.74952589e-19, 1.00000000e+00]])

In [33]:
clf.predict_proba(X)[0,0]

0.9999999847700162

In [36]:
clf.classes_

array([1, 2])

In [39]:
a = np.random.rand(3,2)
a

array([[0.6725621 , 0.89397463],
       [0.19092206, 0.05399999],
       [0.41412395, 0.27799896]])

In [40]:
np.argmax(a)

1

In [7]:
#Pode-se também treinar com partial_fit
clf_pf = GaussianNB()
clf_pf.partial_fit(X, Y, np.unique(Y))

GaussianNB(priors=None, var_smoothing=1e-09)

In [8]:
print("pos- partial_fit", clf_pf.predict([[-0.8, -1]]))

pos- partial_fit [1]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])