In [53]:
from sklearn import datasets
import tensorflow as tf
import numpy as np

In [54]:
#https://archive.ics.uci.edu/ml/datasets/Iris
iris = datasets.load_iris()
#Attributes
#1. sepal length in cm
#2. sepal width in cm
#3. petal length in cm
#4. petal width in cm

#Class:
#-- Iris Setosa
#-- Iris Versicolour
#-- Iris Virginica

In [55]:
X = iris.data

In [56]:
y = iris.target

In [57]:
#Padronização: 
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)
X

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [58]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)
X

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [59]:
#One hot encoding: adjust the data format to network exit layer format: 3 columns equal to 3 exit neurons equals to 3 classes!
"""
[0]         [1][0][0]       Setosa
[1]    to   [0][1][0]       Versicolour
[2]         [0][0][1]       Virginica

"""
from sklearn.preprocessing import OneHotEncoder
onehot = OneHotEncoder(categorical_features = [0])
y.shape

(150,)

In [60]:
y = y.reshape(-1, 1)
y.shape

(150, 1)

In [61]:
y = onehot.fit_transform(y).toarray()
y

C:\Users\Allan Santos\.conda\envs\AM\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Allan Santos\.conda\envs\AM\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [62]:
#trainning and test data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [63]:
X_train.shape

(105, 4)

In [64]:
X_test.shape

(45, 4)

In [65]:
neurons_input_layer = X.shape[1] #
neurons_input_layer

4

In [66]:
#Formula to discover the number of neurons in hidden layer: (number of atts PLUS number of classes) DIVIDED BY 2
neurons_hidden_layer = int(np.ceil((X.shape[1] + y.shape[1]) / 2))
neurons_hidden_layer

4

In [67]:
neurons_exit_layer = y.shape[1]
neurons_exit_layer

3

In [68]:
W = {'hidden': tf.Variable(tf.random_normal([neurons_input_layer, neurons_hidden_layer])),
     'exit': tf.Variable(tf.random_normal([neurons_hidden_layer, neurons_exit_layer]))}

In [69]:
b = {'hidden': tf.Variable(tf.random_normal([neurons_hidden_layer])),
     'exit': tf.Variable(tf.random_normal([neurons_exit_layer]))}

In [70]:
#Using placeholders: 
xph = tf.placeholder('float', [None, neurons_input_layer])
yph = tf.placeholder('float', [None, neurons_exit_layer])

In [71]:
def mlp(X, W, bias):
    hidden_layer = tf.add( tf.matmul( X, W['hidden']), bias['hidden'] )
    hidden_layer_activation = tf.nn.relu(hidden_layer)
    
    exit_layer = tf.add( tf.matmul( hidden_layer_activation, W['exit']), bias['exit'] )
    return exit_layer

In [73]:
model = mlp(xph, W, b)