In [1]:
from gensim.models import Word2Vec

In [9]:
sentences = [['this', 'is', 'the', 'good', 'machine', 'learning', 'book'],
            ['this', 'is',  'another', 'book'],
            ['one', 'more', 'book'],
            ['this', 'is', 'the', 'new', 'post'],
            ['this', 'is', 'about', 'machine', 'learning', 'post'], 
            ['orange', 'juice', 'is', 'the', 'liquid', 'extract', 'of', 'the', 'fruit'],
            ['orange', 'juice', 'comes', 'in', 'several', 'different', 'varieties'],
            ['and', 'this', 'is', 'the', 'last', 'post']]

In [25]:
#embbeding size = 100
model = Word2Vec(sentences, min_count=1, size=100)
vocab = model.wv.vocab.keys()
#vocab = model.vocab.keys()
wordsInVocab = len(vocab)
print('words in vocab: ', wordsInVocab)
print (model.similarity('post', 'book')) 

words in vocab:  26
0.14279845


C:\Users\Allan Santos\.conda\envs\AM\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: Call to deprecated `similarity` (Method will be removed in 4.0.0, use self.wv.similarity() instead).
  


In [46]:
model['book'].shape

C:\Users\Allan Santos\.conda\envs\AM\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


(100,)

In [44]:
#model['post'].shape
model.wv.__getitem__('post') 

array([ 3.9130314e-03, -4.8656703e-04, -3.7094073e-03,  3.8790342e-03,
        3.4173666e-03, -5.3736079e-04,  2.1665089e-03, -4.8409593e-03,
        2.4617449e-03,  7.0433214e-04, -2.9727581e-03,  1.9551544e-03,
        8.6002117e-05, -1.9428448e-03,  9.0020191e-04, -2.2273168e-03,
        2.0143022e-03,  4.4947182e-04,  6.7411907e-05,  1.5354299e-03,
       -3.2944046e-03, -3.7541301e-03, -2.9581273e-03,  4.8234542e-03,
       -1.2831853e-04, -1.7272996e-03, -4.6924856e-03,  4.3779099e-03,
        2.9601590e-03,  2.0051606e-03,  4.2099697e-03,  1.9432944e-03,
       -3.1817188e-03, -3.3523487e-03,  4.8688804e-03,  4.0630829e-03,
       -3.6006833e-03, -1.0752113e-03, -1.4529920e-03, -1.3796366e-03,
       -1.4299072e-03, -2.9657220e-05,  1.4245530e-03, -4.3098762e-04,
        1.8426932e-03,  1.6093147e-03,  3.3115479e-03,  4.9450244e-03,
        3.2893295e-04,  4.8569920e-03,  3.7863682e-04,  4.1657230e-03,
       -1.8801286e-03, -2.6249792e-03, -8.2395232e-04,  4.1372688e-03,
      

In [45]:
model.wv.__getitem__('book') 

array([-2.7434132e-03,  3.6404908e-03,  1.9748688e-03,  4.4759810e-03,
       -1.7293307e-03,  6.7555701e-04,  4.3302467e-03, -2.1244455e-03,
       -2.6923290e-03,  2.0080227e-03,  1.8753273e-05,  2.4566355e-03,
       -1.0389391e-03, -3.9405590e-03, -5.0802424e-04,  4.2147939e-03,
        4.2179497e-03, -3.0572445e-03,  4.3410975e-03, -2.9469898e-03,
       -3.4509993e-03,  5.8436545e-04,  4.7644549e-03,  3.6168320e-03,
       -4.8208493e-03,  9.1294052e-05, -3.4309474e-03,  1.7277302e-03,
        4.2352024e-03,  1.3163957e-03,  4.7499463e-03, -6.9117133e-04,
       -3.0437661e-03,  1.4166406e-03,  4.3331494e-04,  2.5782299e-03,
       -3.9040388e-03,  3.7876365e-03, -4.1162670e-03, -2.6294757e-03,
        2.7954802e-03, -3.2070852e-03,  2.4874532e-03, -1.9329555e-03,
        7.3214801e-04, -4.0591736e-03, -1.3630140e-04,  1.4597587e-03,
       -2.9531263e-03,  7.4602017e-04, -3.5289410e-03, -4.5833434e-03,
        4.4579902e-03, -1.4154610e-03,  5.1281496e-04,  7.3832512e-04,
      

In [69]:
import numpy as np
 
def sent_vectorizer(sentence_array, model):
    
    #vector for each sentence
    sent_vec = np.zeros(100)
    
    #number of words
    numw = 0 

    #for in sentence, word by word (w by w)
    for w in sentence_array:
        try:
            #model[w] is a embbeding (matrix) representation of the word w
            sent_vec = np.add(sent_vec, model[w])
            #print(sent_vec,'\n')
            #print(w,'\n')
            numw+=1 #counter
        except:
            pass
 
    return sent_vec / np.sqrt(sent_vec.dot(sent_vec))

In [71]:
#test:
my_word = sentences[0]
my_word

['this', 'is', 'the', 'good', 'machine', 'learning', 'book']

In [72]:
sent_vectorizer(my_word, model)

C:\Users\Allan Santos\.conda\envs\AM\lib\site-packages\ipykernel_launcher.py:15: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  from ipykernel import kernelapp as app


array([ 0.08246744,  0.05630752,  0.12776424,  0.06662572, -0.00658312,
       -0.03302278, -0.14219772,  0.11775502, -0.07005331, -0.12954468,
        0.0880727 ,  0.11110333, -0.09008793, -0.19726028,  0.09413116,
        0.08067621,  0.04292691,  0.06884543,  0.11887641, -0.00861042,
       -0.14323871,  0.05667008,  0.15034739,  0.03044938, -0.1868967 ,
        0.13378373,  0.17771789,  0.02746044,  0.08336929, -0.0615005 ,
        0.23812369,  0.0610391 ,  0.03565153,  0.09537079,  0.06424216,
       -0.02161871, -0.07050552, -0.03673675,  0.02468971,  0.0911842 ,
       -0.03657679, -0.24384631,  0.02056566,  0.03425388, -0.20298784,
       -0.15118342,  0.02476294,  0.0184942 , -0.09754925,  0.05171479,
       -0.06408281,  0.01694303, -0.02225408,  0.03911296,  0.08389923,
        0.04443269, -0.08447099, -0.20983539,  0.14435786, -0.03975992,
        0.00516352, -0.0285826 , -0.18328891, -0.01719976,  0.0836587 ,
        0.12966483,  0.02371609, -0.13180779,  0.00808612, -0.04

In [73]:
#vocabulary LIST: a list containing each sentence that will be vectorized
V=[]

#for in each sentence from matrix of sentences
for sentence in sentences:
    V.append(sent_vectorizer(sentence, model))

C:\Users\Allan Santos\.conda\envs\AM\lib\site-packages\ipykernel_launcher.py:15: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  from ipykernel import kernelapp as app


In [75]:
type(V)

list

In [81]:
# V is a list contaning 8 sentences vectorized
len(V)

8

In [84]:
from numpy import dot
from numpy.linalg import norm

results = [[0 for i in range(len(V))] for j in range(len(V))] 
print(results, '\n\n')

#from index [0] to [7]
for i in range (len(V) - 1):
    for j in range(i+1, len(V)):
        
         #measuring SIMILARITY? 
        results[i][j] = dot(V[i],V[j])/norm(V[i])/norm(V[j])
 
 
print (results)

[[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]] 


[[0, 0.48628675659894616, 0.21789673228346268, 0.5001731177229513, 0.6369015470995704, 0.35920403280149926, 0.12710250987708702, 0.4406317691069045], [0, 0, 0.2679079189990411, 0.3470464465705319, 0.3583087020627382, 0.18534657010058803, 0.1215339324056778, 0.3684652262378986], [0, 0, 0, 0.15679411688964462, 0.009568733433535816, 0.08281696864156465, 0.09615286982401605, 0.16191445076609765], [0, 0, 0, 0, 0.5053488181651911, 0.5083770411442853, 0.10302209026632986, 0.7753549598011257], [0, 0, 0, 0, 0, 0.22559641791187424, 0.10090083335373037, 0.4749494585547026], [0, 0, 0, 0, 0, 0, 0.36315617255135246, 0.4481099955142719], [0, 0, 0, 0, 0, 0, 0, -0.01549600122179605], [0, 0, 0, 0, 0, 0, 0, 0]]


In [85]:
type(results)

list

In [90]:
results[2]

[0,
 0,
 0,
 0.15679411688964462,
 0.009568733433535816,
 0.08281696864156465,
 0.09615286982401605,
 0.16191445076609765]